apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-admin-password: Q2xhcnVzd2F5XzE=
  mysql-root-password: UjEyMzRy

# Clarusway_1 and R1234r code
#echo -n 'R1234r' | base64  
#echo -n 'Clarusway_1' | base64 

# Clarusway_1 and R1234r decode
# echo -n 'UjEyMzRy' | base64 --decode     
# echo -n 'Q2xhcnVzd2F5XzE=' | base64 --decode